### ISSUE TITLE
2019 Hyundai Kona EV calling wrong start_climate method

### ISSUE THREAD

**Issue by Kevr0n228** [fuatakgun/kia_uvo#214] opened 2021-12-20 00:36 UTC
I just updated to v1.26 after working with @cdnninja to get climate working in Hyundai EVs and it working after taking the update. I did some poking around in the code and was able to determine that it was calling `start_climate` instead of `start_climate_ev` as a result of this check on line 195 of Vehicle.py not evaluating to true:

`if self.engine_type == VEHICLE_ENGINE_TYPE.EV and self.region == REGION_CANADA:`

it seems that `self.region` does not equal `REGION_CANADA` ("Canada"), and from what I could tell it isn't even a string. Printing it out with `_LOGGER.debug` errored out saying it was an int, and when cast to a string it evaluated to '2' - possibly related to `REGION_CANADA`'s position in the `REGIONS` dictionary? I solved it for myself by commenting out part of the condition that checks the region, but I couldn't come up with a proper fix for everyone else.

**Comment by cdnninja** [comment] 2021-12-20 01:28
What region are you in?    Assuming not Canada you should have it running start_climate and never start_climate_ev.   Currently only Canada needs a separate EV command.  This is probably something we could clean up to make more clear.   

You are correct in that neither of those values are a string but rather a number.

**Comment by cdnninja** [comment] 2021-12-20 01:28
Before commenting out what error or issue were you seeing?

**Comment by Kevr0n228** [comment] 2021-12-20 13:01
I am in Canada - sorry for not including that in the first post.

**Comment by zadigre** [comment] 2021-12-20 15:21
I have a 2021 Kona Electric. 
Climate is not starting with the climate_start service. 
all other sensors/services (like door unlock/lock) seem to work fine. 
I'm also in Canada.

I'm not confortable editing the python file directly. So I guess I'll wait for the next update that may include a fix.

**Comment by cdnninja** [comment] 2021-12-20 15:47
@Kevr0n228 are you able to test out #216?

**Comment by cdnninja** [comment] 2021-12-20 17:07
@zadigre if you reload in HACS from "master" it will work now.    Other option is a new release number will come out Wednesday.

**Comment by zadigre** [comment] 2021-12-20 17:37
@cdnninja 
confirmed working fine on "master". 

thank you!

**Comment by zadigre** [comment] 2021-12-20 18:50
@cdnninja 
although it's working fine to start climate, when I use the "stop climate" service, it doesn't stop the defrost (yes confirmed in my car... front defrost still enabled and running)... but Air Conditionner, Steering Wheel Heater and Back Window Heater are stopped properly. 

is this a bug in the integration or it's just the way it is for my car/Bluelink?

to make the defroster stop, I had to run start climate with "Defroster: False" and then run stop climate service.

**Comment by cdnninja** [comment] 2021-12-20 19:00
@zadigre could you test with the app to see if you get the same thing? The command we currently send doesn't specify what to turn off just a general off command.  Maybe we can specify though.

**Comment by zadigre** [comment] 2021-12-20 19:35
@cdnninja I saw the other thread that said 1 out of 10 times, front defrost does not disable itself in the app when stopping climate.
And yes I see the same behaviour in the app (I never experienced this before because I never had to turn off climate. 

that said, starting climate is a little bit buggy with my car/Bluelink... I have to enable defrost to get it to start without any error in the app. Others on Reddit have said they experienced the exact same thing. So I guess the stop problem might be related to this same issue.

**Comment by cdnninja** [comment] 2021-12-20 20:05
@zadigre good to know this isn't our implementation.

**Comment by cdnninja** [comment] 2021-12-20 20:49
I am going to close this again as it looks like the OP's issue is solved.

**Closed by cdnninja** 2021-12-20 20:49 UTC
Labels: bug, Canada
