### ISSUE TITLE
Issue with USA KIA implementation

### ISSUE THREAD

**Issue by mc130420** [fuatakgun/kia_uvo#100] opened 2021-11-04 15:46 UTC
Getting an error upon installation (Region = USA and  Brand = KIA.  Log error below.  I looked at the vehicle object and it seems to be expecting the attribute self.model to be populated with the vehicle model attribute on the token which does not exist on the UsaToken.   I believe it can be pulled out of the json response with  vehicle_model = vehicle_summary[0]['modelName'].

vehicle: Vehicle = Vehicle(
File "/config/custom_components/kia_uvo/Vehicle.py", line 40, in __init__
self.model = token.vehicle_model
AttributeError: 'Token' object has no attribute 'vehicle_model'

**Comment by josephkiser04** [comment] 2021-11-04 16:58
Same issue here.

**Comment by dahlb** [comment] 2021-11-06 18:04
I have the same issue, but I think this is a duplicate of https://github.com/fuatakgun/kia_uvo/issues/88

**Comment by cdnninja** [comment] 2021-11-06 21:07
Yes it is covered in that as well if anyone has a chance to try fix it please try and create a PR.

**Comment by cdnninja** [comment] 2021-11-07 02:19
Added the vehicle model to the USA token as a short term fix.  It is located here.  Could someone test and let me know: https://github.com/fuatakgun/kia_uvo/tree/USAKia

**Comment by dahlb** [comment] 2021-11-07 18:08
using USAKia I got this log (new error)

```
2021-11-07 12:58:52 DEBUG (SyncWorker_1) [custom_components.kia_uvo.KiaUvoAPIUSA] kia_uvo - Sign In Response {"status":{"statusCode":0,"errorType":0,"errorCode":0,"errorMessage":"Success with response body"}}
2021-11-07 12:58:52 DEBUG (SyncWorker_1) [custom_components.kia_uvo.KiaUvoAPIUSA] got session id 284
2021-11-07 12:58:53 DEBUG (SyncWorker_1) [custom_components.kia_uvo.KiaUvoAPIUSA] kia_uvo - Get Vehicles Response {"status":{"statusCode":0,"errorType":0,"errorCode":0,"errorMessage":"Success with response body"},"payload":{"vehicleSummary":[{"vin":"vvv","vehicleIdentifier":"000","modelName":"NIRO EV","modelYear":"2019","nickName":"Niro EV","generation":2,"extColorCode":"C3S","trim":"EX PREMIUM","imagePath":{"imageName":"2019-niro_ev-ex_premium-c3s.png","imagePath":"/content/dam/kia/us/owners/image/vehicle/2019/niro_ev/ex_premium/","imageType":"1","imageSize":{"length":"100","width":"100","uom":0}},"enrollmentStatus":1,"fatcAvailable":1,"telematicsUnit":1,"fuelType":4,"colorName":"ALUMINUM SILVER","activationType":2,"mileage":"12089.4","dealerCode":"MD047","mobileStore":[{"osType":0,"downloadURL":"https://itunes.apple.com/us/app/kia-access-with-uvo-link/id1280548773?mt=8","image":{"imageName":"iosImage.png","imagePath":"/content/dam/kia/us/owners/image/common/app/","imageType":"2","imageSize":{"length":"100","width":"100","uom":0}}},{"osType":1,"downloadURL":"https://play.google.com/store/apps/details?id=com.myuvo.link","image":{"imageName":"androidImage.png","imagePath":"/content/dam/kia/us/owners/image/common/app/","imageType":"2","imageSize":{"length":"100","width":"100","uom":0}}}],"supportedApp":{"appType":"5","appImage":{"imageName":"uvo-app.png","imagePath":"/content/dam/kia/us/owners/image/common/app/access/","imageType":"2","imageSize":{"length":"100","width":"100","uom":0}}},"supportAdditionalDriver":0,"customerType":0,"projectCode":"DEEV","headUnitDesc":"AVN5.0","provStatus":"4","enrollmentSuppressionType":0,"vehicleKey":"kkk"}]}}
2021-11-07 12:58:53 DEBUG (MainThread) [custom_components.kia_uvo] kia_uvo - async_setup_entry started - <homeassistant.config_entries.ConfigEntry object at 0x7f8efc950ca0>
2021-11-07 12:58:53 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry email for kia_uvo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/kia_uvo/__init__.py", line 134, in async_setup_entry
    vehicle: Vehicle = Vehicle(
  File "/config/custom_components/kia_uvo/Vehicle.py", line 42, in __init__
    self.registration_date = token.vehicle_registration_date
AttributeError: 'Token' object has no attribute 'vehicle_registration_date'
```

I'm new to this code base but very excited at the idea of a more reliable interface for controlling my car.  Please let me know if I can provide any other logs, or if I striped some information that would've been useful.

**Comment by dahlb** [comment] 2021-11-07 18:37
it looks like that next error is about an attribute that doesn't exist in USA and is only used for entity 'sw_version' so this seems a quick fix, though a better fix might be to just log that and not throw it in device_info for KiaUvoEntity.py as it isn't really a sw_version anyway
```
diff --git a/custom_components/kia_uvo/Token.py b/custom_components/kia_uvo/Token.py
index 5c06534..03acc47 100644
--- a/custom_components/kia_uvo/Token.py
+++ b/custom_components/kia_uvo/Token.py
@@ -33,6 +33,7 @@ class UsaToken(Token):
         self.vehicle_name = vehicle_name
         self.vehicle_key = vehicle_key
         self.vehicle_model = vehicle_model
+        self.vehicle_registration_date = 'unknown'
 
     def expire(self):
         pass
```

**Comment by dahlb** [comment] 2021-11-07 18:41
next error was about token refreshing, I'm likely missing something but from what I saw in the logs I didn't see any expiration so this might be a valid fix

```
diff --git a/custom_components/kia_uvo/Token.py b/custom_components/kia_uvo/Token.py
index 5c06534..c194ef7 100644
--- a/custom_components/kia_uvo/Token.py
+++ b/custom_components/kia_uvo/Token.py
@@ -33,6 +33,8 @@ class UsaToken(Token):
         self.vehicle_name = vehicle_name
         self.vehicle_key = vehicle_key
         self.vehicle_model = vehicle_model
+        self.vehicle_registration_date = 'unknown'
+        self.valid_until = datetime.max.strftime(DATE_FORMAT)
 
     def expire(self):
         pass
```

**Comment by dahlb** [comment] 2021-11-07 18:50
sorry for the noise but I'm going to have to go soon so I'm going to post my lastest logs using KiaUSA with above additions

```
2021-11-07 13:39:42 DEBUG (SyncWorker_0) [custom_components.kia_uvo.KiaUvoAPIUSA] got response {"status":{"statusCode":0,"errorType":0,"errorCode":0,"errorMessage":"Success with response body"},"payload":{"vehicleInfoList":[{"vinKey":"kkk","vehicleConfig":{"vehicleDetail":{"vehicle":{"vin":"vvv","trim":{"modelYear":"2019","salesModelCode":"V1262","optionGroupCode":"015","modelName":"NIRO EV","factoryCode":"DQ","projectCode":"DEEV","trimName":"EX PREMIUM","driveType":"0","transmissionType":"1","ivrCategory":"6","btSeriesCode":"N"},"telematics":1,"mileage":"12089.4","mileageSyncDate":"20211107011820","exteriorColor":"ALUMINUM SILVER","exteriorColorCode":"C3S","fuelType":4,"invDealerCode":"MD047","testVehicle":"0","supportedApps":[{"appType":"0"},{"appType":"5","appImage":{"imageName":"uvo-app.png","imagePath":"/content/dam/kia/us/owners/image/common/app/access/","imageType":"2","imageSize":{"length":"100","width":"100","uom":0}}}],"activationType":2},"images":[{"imageName":"2019-niro_ev-ex_premium-c3s.png","imagePath":"/content/dam/kia/us/owners/image/vehicle/2019/niro_ev/ex_premium/","imageType":"1","imageSize":{"length":"100","width":"100","uom":0}}],"device":{"launchType":"0","swVersion":"DEEV.USA.SOP.V105.190503.STD_H","telematics":{"generation":"3","platform":"1","tmsCenter":"1","billing":true},"versionNum":"ECO","headUnitType":"0","hdRadio":"X40HA","ampType":"NA","modem":{"meid":"meidd","mdn":"mdnn","iccid":"idid"},"headUnitName":"avn40ev_np","bluetoothRef":"10","headUnitDesc":"AVN5.0"}},"billingPeriod":{"freeTrial":{"value":12,"unit":0},"freeTrialExtension":{"value":12,"unit":1},"servicePeriod":{"value":60,"unit":1}}},"lastVehicleInfo":{"vehicleNickName":"Niro EV","preferredDealer":"MD047","customerType":0,"enrollment":{"provStatus":"4","enrollmentStatus":"1","enrollmentType":"0","registrationDate":"20191123","expirationDate":"20201122","expirationMileage":"100000","freeServiceDate":{"startDate":"20191122","endDate":"20201122"}},"activeDTC":{"dtcActiveCount":"0"},"vehicleStatusRpt":{"statusType":"2","reportDate":{"utc":"20211107183941","offset":-8},"vehicleStatus":{"climate":{"airCtrl":false,"defrost":false,"airTemp":{"value":"72","unit":1},"heatingAccessory":{"steeringWheel":0,"sideMirror":0,"rearWindow":0}},"engine":false,"doorLock":false,"doorStatus":{"frontLeft":0,"frontRight":0,"backLeft":0,"backRight":0,"trunk":0,"hood":0},"lowFuelLight":false,"evStatus":{"batteryCharge":false,"batteryStatus":75,"batteryPlugin":0,"remainChargeTime":[{"remainChargeType":1,"timeInterval":{"value":0,"unit":4}},{"remainChargeType":2,"timeInterval":{"value":0,"unit":4}},{"remainChargeType":3,"timeInterval":{"value":140,"unit":4}}],"drvDistance":[{"type":2,"rangeByFuel":{"evModeRange":{"value":212,"unit":3},"totalAvailableRange":{"value":212,"unit":3}}}],"syncDate":{"utc":"20211107151819","offset":-8},"targetSOC":[{"plugType":0,"targetSOClevel":127,"dte":{"type":2,"rangeByFuel":{"gasModeRange":{"value":0,"unit":3},"evModeRange":{"value":212,"unit":3},"totalAvailableRange":{"value":212,"unit":3}}}},{"plugType":1,"targetSOClevel":127,"dte":{"type":2,"rangeByFuel":{"gasModeRange":{"value":0,"unit":3},"evModeRange":{"value":212,"unit":3},"totalAvailableRange":{"value":212,"unit":3}}}}]},"ign3":false,"transCond":true,"tirePressure":{"all":0},"dateTime":{"utc":"20211107183941","offset":-8},"syncDate":{"utc":"20211107151819","offset":-8},"batteryStatus":{"stateOfCharge":86,"sensorStatus":0},"sleepMode":true,"lampWireStatus":{"headLamp":{},"stopLamp":{},"turnSignalLamp":{}},"windowStatus":{},"engineRuntime":{},"valetParkingMode":0}},"location":{"coord":{"lat":30,"lon":-30,"alt":108,"type":0,"altdo":0},"head":342,"speed":{"value":0,"unit":1},"accuracy":{"hdop":6,"pdop":10},"syncDate":{"utc":"20211107151819","offset":-8}},"financed":true,"financeRegistered":true,"linkStatus":0}}]}}
2021-11-07 13:39:42 ERROR (MainThread) [custom_components.kia_uvo.Vehicle] kia_uvo - Exception in update : 'vehicleStatus' - traceback: Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/Vehicle.py", line 55, in update
    self.set_last_updated()
  File "/config/custom_components/kia_uvo/Vehicle.py", line 176, in set_last_updated
    self.vehicle_data["vehicleStatus"]["time"],
KeyError: 'vehicleStatus'

2021-11-07 13:39:42 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry username for kia_uvo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/kia_uvo/__init__.py", line 174, in async_setup_entry
    await update(dt_util.utcnow())
  File "/config/custom_components/kia_uvo/__init__.py", line 165, in update
    if (datetime.now(local_timezone) - vehicle.last_updated > force_scan_interval):
TypeError: can't subtract offset-naive and offset-aware datetimes
```

I'm still new to python so I'll look into this error later but I'm less able to fix it with my existing knowledge.  But great to see real car details in the latest logs.

**Comment by cdnninja** [comment] 2021-11-07 20:11
This is great!  I do think that using a separate token for this is causing us pain.  May of the fields align with something in the normal token just with a different name.  As such I have refactored it to return using the same token as all other regions.  Are you able to retest?  That last error you have it because the time stamp is empty. 

 @fuatakgun and I have been chatting on a few challenges like this since with multiple regions they each have unique issues like this.

**Comment by dahlb** [comment] 2021-11-08 01:21
this diff fixes the next couple errors and I'm not explicitly getting anymore errors
```
diff --git a/custom_components/kia_uvo/KiaUvoAPIUSA.py b/custom_components/kia_uvo/KiaUvoAPIUSA.py
index ec44d30..3733d17 100644
--- a/custom_components/kia_uvo/KiaUvoAPIUSA.py
+++ b/custom_components/kia_uvo/KiaUvoAPIUSA.py
@@ -116,8 +116,20 @@ class KiaUvoAPIUSA(KiaUvoApiImpl):
         #using vehicle_VIN as device ID
         #using vehicle_key as vehicle_regid
         
-        
-        token = Token(session_id, None, vehicle_vin, vehicle_name, vehicle_id, vehicle_key, "Unknown", vehicle_registration_date, valid_until, "NoStamp")
+
+        token = Token({})
+        token.set(
+            session_id,
+            None,
+            vehicle_vin,
+            vehicle_name,
+            vehicle_id,
+            vehicle_key,
+            "Unknown",
+            vehicle_registration_date,
+            valid_until,
+            "NoStamp",
+        )
 
         return token
 
@@ -148,11 +160,16 @@ class KiaUvoAPIUSA(KiaUvoApiImpl):
                     token.vehicle_regid
                 ]
             }
-        _LOGGER.debug(f"sending get vehicle info request ${body} with session id ${token.sid}")
+        _LOGGER.debug(f"sending get vehicle info request ${body} with session id ${token.access_token}")
         response = requests.post(url, json=body, headers=headers)
         _LOGGER.debug(f"got response {response.text}")
         response_body = response.json()
-        return response_body
+        vehicle_data = {
+          "vehicleStatus": response_body["payload"]["vehicleInfoList"][0]["lastVehicleInfo"]["vehicleStatusRpt"]["vehicleStatus"]
+        }
+        vehicle_data["vehicleStatus"]["time"] = vehicle_data["vehicleStatus"]["dateTime"]["utc"]
+        return vehicle_data
+
     def get_location(self, token: Token):
         pass
     def get_pin_token(self, token: Token):
```

though I noticed the engine type is set incorrectly as PHEV even though this is an EV

my vehicle info response for reference is
 vehicleConfig/vehicleDetail/trim(driveType or transmissionType) might better define EV vs others but I don't know what the other region responses look like
```
{"status":{"statusCode":0,"errorType":0,"errorCode":0,"errorMessage":"Success with response body"},"payload":{"vehicleInfoList":[{"vinKey":"kkk","vehicleConfig":{"vehicleDetail":{"vehicle":{"vin":"vvv","trim":{"modelYear":"2019","salesModelCode":"V1262","optionGroupCode":"015","modelName":"NIRO EV","factoryCode":"DQ","projectCode":"DEEV","trimName":"EX PREMIUM","driveType":"0","transmissionType":"1","ivrCategory":"6","btSeriesCode":"N"},"telematics":1,"mileage":"12110.8","mileageSyncDate":"20211107095846","exteriorColor":"ALUMINUM SILVER","exteriorColorCode":"C3S","fuelType":4,"invDealerCode":"MD047","testVehicle":"0","supportedApps":[{"appType":"0"},{"appType":"5","appImage":{"imageName":"uvo-app.png","imagePath":"/content/dam/kia/us/owners/image/common/app/access/","imageType":"2","imageSize":{"length":"100","width":"100","uom":0}}}],"activationType":2},"images":[{"imageName":"2019-niro_ev-ex_premium-c3s.png","imagePath":"/content/dam/kia/us/owners/image/vehicle/2019/niro_ev/ex_premium/","imageType":"1","imageSize":{"length":"100","width":"100","uom":0}}],"device":{"launchType":"0","swVersion":"DEEV.USA.SOP.V105.190503.STD_H","telematics":{"generation":"3","platform":"1","tmsCenter":"1","billing":true},"versionNum":"ECO","headUnitType":"0","hdRadio":"X40HA","ampType":"NA","modem":{"meid":"300","mdn":"400","iccid":"500"},"headUnitName":"avn40ev_np","bluetoothRef":"10","headUnitDesc":"AVN5.0"}},"billingPeriod":{"freeTrial":{"value":12,"unit":0},"freeTrialExtension":{"value":12,"unit":1},"servicePeriod":{"value":60,"unit":1}}},"lastVehicleInfo":{"vehicleNickName":"Niro EV","preferredDealer":"MD047","customerType":0,"enrollment":{"provStatus":"4","enrollmentStatus":"1","enrollmentType":"0","registrationDate":"20191123","expirationDate":"20201122","expirationMileage":"100000","freeServiceDate":{"startDate":"20191122","endDate":"20201122"}},"activeDTC":{"dtcActiveCount":"0"},"vehicleStatusRpt":{"statusType":"2","reportDate":{"utc":"20211108010648","offset":-8},"vehicleStatus":{"climate":{"airCtrl":false,"defrost":false,"airTemp":{"value":"72","unit":1},"heatingAccessory":{"steeringWheel":0,"sideMirror":0,"rearWindow":0}},"engine":false,"doorLock":true,"doorStatus":{"frontLeft":0,"frontRight":0,"backLeft":0,"backRight":0,"trunk":0,"hood":0},"lowFuelLight":false,"evStatus":{"batteryCharge":true,"batteryStatus":80,"batteryPlugin":2,"remainChargeTime":[{"remainChargeType":3,"timeInterval":{"value":95,"unit":4}}],"drvDistance":[{"type":2,"rangeByFuel":{"evModeRange":{"value":227,"unit":3},"totalAvailableRange":{"value":227,"unit":3}}}],"syncDate":{"utc":"20211108005846","offset":-8},"targetSOC":[{"plugType":0,"targetSOClevel":90,"dte":{"type":2,"rangeByFuel":{"gasModeRange":{"value":0,"unit":3},"evModeRange":{"value":227,"unit":3},"totalAvailableRange":{"value":227,"unit":3}}}},{"plugType":1,"targetSOClevel":90,"dte":{"type":2,"rangeByFuel":{"gasModeRange":{"value":0,"unit":3},"evModeRange":{"value":227,"unit":3},"totalAvailableRange":{"value":227,"unit":3}}}}]},"ign3":true,"transCond":true,"tirePressure":{"all":0},"dateTime":{"utc":"20211108010648","offset":-8},"syncDate":{"utc":"20211108005846","offset":-8},"batteryStatus":{"stateOfCharge":87,"sensorStatus":0},"sleepMode":false,"lampWireStatus":{"headLamp":{},"stopLamp":{},"turnSignalLamp":{}},"windowStatus":{},"engineRuntime":{},"valetParkingMode":0}},"location":{"coord":{"lat":10,"lon":-30,"alt":40,"type":0,"altdo":0},"head":345,"speed":{"value":0,"unit":1},"accuracy":{"hdop":7,"pdop":13},"syncDate":{"utc":"20211108005846","offset":-8}},"financed":true,"financeRegistered":true,"linkStatus":0}}]}}
```

**Comment by dahlb** [comment] 2021-11-08 01:30
I got an error about session expiring when exploring entities try to verify things and reloaded the integration.  I'm not aware of best practices to intercept that response and re-authenticate before retrying.

```
2021-11-07 20:24:59 DEBUG (SyncWorker_5) [custom_components.kia_uvo.KiaUvoAPIUSA] got response {"status":{"statusCode":1,"errorType":1,"errorCode":1003,"errorMessage":"Session Key is either invalid or expired"}}
2021-11-07 20:24:59 ERROR (MainThread) [custom_components.kia_uvo.Vehicle] kia_uvo - Exception in update : 'payload' - traceback: Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/Vehicle.py", line 54, in update
    self.vehicle_data = await self.hass.async_add_executor_job(self.kia_uvo_api.get_cached_vehicle_status, self.token)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/kia_uvo/KiaUvoAPIUSA.py", line 168, in get_cached_vehicle_status
    "vehicleStatus": response_body["payload"]["vehicleInfoList"][0]["lastVehicleInfo"]["vehicleStatusRpt"]["vehicleStatus"]
```

**Comment by cdnninja** [comment] 2021-11-08 01:32
Just did a commit against the USAKia branch.  Give it a shot to see if I corrected as per your above comments.  Feel free to create a PR to that branch as well.   

As for the session. I just left the session as being 24 hour expiry.  We don't know how log it actually lasts.   In the commit I just did I dropped that to 1 hour since it sounds like it expired pretty quickly.

**Comment by cdnninja** [comment] 2021-11-08 01:33
Are any data points showing in HA now? or just error free and blank?

**Comment by dahlb** [comment] 2021-11-08 01:48
<img width="837" alt="Screen Shot 2021-11-07 at 8 40 43 PM" src="https://user-images.githubusercontent.com/54117/140671521-abfcf0c0-c2ab-41b6-a9dc-9e34b9fbbd18.png">

I haven't checked the engine on/off yet
also haven't figured out how to verify location yet as I think I have to enable a preference though I've seen it in the response I've been sanitizing
both ranges say 365.3 km, but should be 197 mi (I haven't set the unit preference as I just keep recreating)

all other showing in shot above seem to be populating correctly.

I think the session expires based on idle time between requests based on prior app usage, and based on when it appeared earlier in testing it might be incredible short like 5 minutes range

**Comment by dahlb** [comment] 2021-11-08 01:57
reverted to KiaUSA and verified same results as above, thanks :) looking great. I'll try to put any future changes into a pr for convenience.  I can only check in twice a day and am about to head to sleep, please let me know what to look into next.

**Comment by cdnninja** [comment] 2021-11-08 01:58
That is a great start.  We may need to shorten the token window to something in the 5 minute range and see if that resolves it.   I think this is the first implementation for Kia USA so learning as we go! 


Glad to see data is starting to work.   I am thinking we continue this conversation over at #88.

**Comment by cdnninja** [comment] 2021-11-08 02:28
@dahlb as for next steps it is really up to the USA Kia users on what they see.  I am running blind on this without access.  Closing this issue in favor of 88.

**Closed** 2021-11-08 02:29 UTC
