### ISSUE TITLE
Support for Hyundai India

### ISSUE THREAD

**Issue by vmax77** [fuatakgun/kia_uvo#346] opened 2022-08-14 11:39 UTC
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Would like to be able to choose the country of Bluelink account. 

**Include the logs of the end point from Data in HA if this is a sensor**

**Describe alternatives you've considered**

**Additional context**

**Comment by cdnninja** [comment] 2022-08-14 22:21
This is duplicate of #337.  We will need someone to sniff the traffic.

**Closed** 2022-08-14 22:22 UTC

**Comment by cdnninja** [comment] 2025-04-19 21:09
Thanks to @nishant713  this has been added to the master branch.  Next release will include it.
