### ISSUE TITLE
Hyundai USA Sensor Unavailable State While Updating

### ISSUE THREAD

**Issue by AndrewDaws** [fuatakgun/kia_uvo#197] opened 2021-12-02 18:41 UTC
Hello,

I am having an issue with many of the sensors (I think all the binary sensors) are going to the "unavailable" state for a few seconds while the integration is scanning (default 30 minute scan time), as shown in the attached screenshot.

![Screenshot from 2021-12-02 13-27-59](https://user-images.githubusercontent.com/5349812/144482011-fe057589-4aa5-4004-9ee9-399db658f5bf.png)

I am not sure why exactly the sensors states are being updated before the scan is completed. As a result it makes it rather difficult to figure out when the states *actually* changed.

**Comment by fuatakgun** [comment] 2021-12-02 19:52
can you dump your Data entity when happens next time?

**Comment by cdnninja** [comment] 2021-12-03 03:00
Is this using the current version? 1.2.1?

**Comment by cdnninja** [comment] 2021-12-03 16:45
Once we have logs we can confirm but I am wondering if this occurs when the token expires.  I think the token on Kia USA is very short lived so I suspect it is logging in each time to grab the values.  I will try replicate by forcing my region to a short token TTL.

**Comment by edwork** [comment] 2021-12-08 03:09
I can confirm this is happening hourly on my USA based 2021 Kia Sorento. I am currently running version 1.2.2.  



![image](https://user-images.githubusercontent.com/1832400/145141442-ee36874b-80fe-486f-9953-99a9c2c2dae2.png)

**Comment by AndrewDaws** [comment] 2021-12-09 12:40
Sorry for the delay.

It looks like the login token is expiring each time it tries to refresh my vehicle, and it must be during that token acquisition period that it is making the states "Unavailable". 


> 2021-12-09 07:00:09 DEBUG (MainThread) [custom_components.kia_uvo.Vehicle] kia_uvo - Refresh token started 2021-12-09 07:00:04.851854 2021-12-09 07:00:09.210144 True
> 2021-12-09 07:00:09 DEBUG (MainThread) [custom_components.kia_uvo.Vehicle] kia_uvo - **Refresh token expired**
> 2021-12-09 07:00:09 DEBUG (SyncWorker_6) [custom_components.kia_uvo.HyundaiBlueLinkAPIUSA] kia_uvo - Sign In Response ...


Versions:
Home Assistant = 2021.12.0b4
Kia Uvo / Hyundai Bluelink = v1.2.2

**Comment by cdnninja** [comment] 2021-12-12 22:04
Just for kick could you make your refresh cycle 29 minutes?   I am wondering if that changes the behavior at all.

**Comment by AndrewDaws** [comment] 2021-12-13 19:21
> Just for kick could you make your refresh cycle 29 minutes? I am wondering if that changes the behavior at all.

@cdnninja Unfortunately changing the refresh cycle to 29 minutes didn't seem to make any difference at all. Still have the various sensors going "Unavailable" for a few seconds during refresh. I am even on the latest and greatest version v1.2.3.

**Comment by fuatakgun** [comment] 2021-12-21 16:18
so, this is both happening in USA and CA, is that correct?

**Comment by chrisgilldc** [comment] 2021-12-21 16:22
I'm definitely seeing this behavior with my 2022 Kona Electric in the US.

**Comment by fuatakgun** [comment] 2021-12-21 16:28
@cdnninja , I have gone through logs below, my findings;
- 07:00:09 - Refresh token started 07:00:04 - 07:00:09 True - TOKEN NEEDS TO BE REFRESHED - 09 is greater than 04
- 07:00:10 - Refresh token started 07:30:09 - 07:00:10 False - No need to refresh as 09 is less than 10
The problem is here, token is to be expired just in 30 minutes? it was supposed to be daily, or I am wrong?

- In EU, it is set to expire in 23 hours: https://github.com/fuatakgun/kia_uvo/blob/master/custom_components/kia_uvo/KiaUvoApiEU.py#L123
- In CA, it is set to expire in 23 hours: https://github.com/fuatakgun/kia_uvo/blob/master/custom_components/kia_uvo/KiaUvoApiCA.py#L95
- In US, it is set to expire in 1 hour: https://github.com/fuatakgun/kia_uvo/blob/master/custom_components/kia_uvo/KiaUvoAPIUSA.py#L195

**Comment by cdnninja** [comment] 2021-12-21 16:34
Hyundai USA has a very short token which makes this more apparent.  It occurs with longer tokens as well.

**Comment by fuatakgun** [comment] 2021-12-21 16:36
got it, but when sensors become unavailable under these logs? https://github.com/fuatakgun/kia_uvo/issues/197#issuecomment-989815946

**Comment by cdnninja** [comment] 2021-12-21 16:40
You somewhat need to coordinate it with the home assistant GUI.  Using the test API I set the token very short so that I can easily replicate., I can't seem to find the cause though.

**Comment by fuatakgun** [comment] 2021-12-21 16:42
hey, I also have in my local instance :) easier to debug now

![image](https://user-images.githubusercontent.com/11085566/146966661-558e9213-52d6-4fc0-8189-6f18cb14f09b.png)

**Comment by fuatakgun** [comment] 2021-12-21 16:44
yes, you are right, it is happening when token is expired and it needs to be refreshed, reading the code to find the culprit

**Comment by fuatakgun** [comment] 2021-12-21 16:47
updating config_entry might be causing to reload all entities: 

```
            hass.config_entries.async_update_entry(
                config_entry, data=new_data, options=config_entry.options
            )
```
https://github.com/fuatakgun/kia_uvo/blob/cff4b711ebf7bcc69b1ac8c22361c69feea926e5/custom_components/kia_uvo/__init__.py#L190

**Comment by fuatakgun** [comment] 2021-12-21 16:53
yes, it is clear that reloading or updating the config_entry is causing this. next question, how can we avoid this?
![image](https://user-images.githubusercontent.com/11085566/146968369-629e4b5f-ba4b-40d6-9186-fecd4ee17668.png)

**Comment by fuatakgun** [comment] 2021-12-21 16:55
@cdnninja , to help US users, can we extend 30 minutes expiration to 1 day? at least, issue will happen less and will impact less. Of course, we should continue investigation to find out solution.

**Comment by cdnninja** [comment] 2021-12-21 16:57
From my understanding this is the Hyundai Token duration.  It expires that quickly.    I believe we are calculating it from the response right now.

**Comment by cdnninja** [comment] 2021-12-21 18:02
> updating config_entry might be causing to reload all entities:
> 
> ```
>             hass.config_entries.async_update_entry(
>                 config_entry, data=new_data, options=config_entry.options
>             )
> ```
> 
> https://github.com/fuatakgun/kia_uvo/blob/cff4b711ebf7bcc69b1ac8c22361c69feea926e5/custom_components/kia_uvo/__init__.py#L190

Could we do this on unload instead?

**Comment by fuatakgun** [comment] 2021-12-21 18:13
You are right, we can do it while unloading or home assistant shutdown event. Idea behind was to keep latest credentials always up to date, so we don't need to over consume api calls.

**Comment by fuatakgun** [comment] 2022-01-14 22:03
This should have been resolved, thanks @cdnninja

**Comment by cdnninja** [comment] 2022-01-16 17:39
This is now merged and released.   Let us know if you think it still occurs.

**Closed by cdnninja** 2022-01-16 17:39 UTC
