### ISSUE TITLE
integration is not working (failing after couple of minutes or at all)

### ISSUE THREAD

**Issue by nilrog** [fuatakgun/kia_uvo#285] opened 2022-02-07 17:43 UTC
**Car/Region**
Hyundai Ioniq 5, EU

**Describe the bug**
After the release of v1.4.6 that fixed the failure from this morning I have only partial success. The integration breaks after restart.

After I updated kia_uvo through HACS and restarted, all sensors was unavailable. I then tried deleting the integration and adding back the integration thinking that it was needed to refresh any token that might be stored. And when I added it back it started working.
I then restarted HA due to another reason and it stopped working. I have tested this twice now and the behavior is the same. It works when I add it, but stops working after restart. The second time I also restarted HA between removing the integration and adding it back. The behavior is the same.

**Debug logs if an error occurred**

Note: I have masked tokens and some other data.
```
2022-02-07 18:25:06 DEBUG (MainThread) [custom_components.kia_uvo] kia_uvo - async_setup_entry started - <homeassistant.config_entries.ConfigEntry object at 0x7fb347c8c3b0>
2022-02-07 18:25:06 DEBUG (MainThread) [custom_components.kia_uvo.Vehicle] kia_uvo - Received token into Vehicle Object {'valid_until': '2022-02-08 17:21:27.494804', 'access_token': 'Bearer **********', 'refresh_token': 'Bearer **********', 'device_id': '**********', 'vehicle_name': 'IONIQ 5', 'vehicle_id': '**********', 'vehicle_regid': None, 'vehicle_model': 'IONIQ 5', 'vehicle_registration_date': '**********', 'stamp': '**********'}
2022-02-07 18:25:06 DEBUG (MainThread) [custom_components.kia_uvo.Vehicle] kia_uvo - Refresh token started 2022-02-08 17:21:27.494804 2022-02-07 18:25:06.537597 False
2022-02-07 18:25:06 DEBUG (SyncWorker_4) [custom_components.kia_uvo.KiaUvoApiEU] kia_uvo - get_cached_vehicle_status response {'retCode': 'F', 'resCode': '4017', 'resMsg': 'Invalid request value - Invalid Application Id. - 670.7019999027252', 'msgId': '**********'}
2022-02-07 18:25:08 ERROR (MainThread) [custom_components.kia_uvo.Vehicle] kia_uvo - Exception in update : string indices must be integers - traceback: Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/Vehicle.py", line 56, in update
    self.vehicle_data = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/kia_uvo/KiaUvoApiEU.py", line 433, in get_cached_vehicle_status
```

```
cat custom_components/kia_uvo/manifest.json
{
  "domain": "kia_uvo",
  "name": "Kia Uvo / Hyundai Bluelink",
  "documentation": "https://github.com/fuatakgun/kia_uvo",
  "issue_tracker": "https://github.com/fuatakgun/kia_uvo/issues",
  "codeowners": ["@fuatakgun"],
  "requirements": ["push_receiver==0.1.1", "curlify", "bs4"],
  "version": "1.4.6",
  "config_flow": true,
  "iot_class": "cloud_polling"
}
```

**To Reproduce**
1: Remove the kia_uvo integration from HA
2. Restart HA
3. Add the kia_uvo integration
4. Confirm that it is working
5. Restart HA
6. The kia_uvo integration stops working

**Expected behavior**
The kia_uvo integration working after HA restart without having to delete/add it again.

**Comment by egyroloine** [comment] 2022-02-07 18:54
It stopped working here as well now.

**Comment by cdnninja** [comment] 2022-02-07 19:13
Could someone try manually place this file changes into your home assistant?  I am not from EU so can't help test.  #287

**Comment by ArnodeParno** [comment] 2022-02-07 19:17
After the last update it did not work anymore..

**Comment by cdnninja** [comment] 2022-02-07 19:23
@ArnodeParno as in the code I posted or do you mean the last releases update?

**Comment by LuckyTriple7** [comment] 2022-02-07 19:39
> Could someone try manually place this file changes into your home assistant? I am not from EU so can't help test. #287

I replaced KiaUvoApiEU.py and Restart HA, but Entities are still unavailable after Restart ...

```
2022-02-07 20:35:45 ERROR (MainThread) [custom_components.kia_uvo.Vehicle] kia_uvo - Exception in update : string indices must be integers - traceback: Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/Vehicle.py", line 56, in update
    self.vehicle_data = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/kia_uvo/KiaUvoApiEU.py", line 433, in get_cached_vehicle_status
    return response["resMsg"]["vehicleStatusInfo"]
TypeError: string indices must be integers

2022-02-07 20:35:45 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry xxx@xxx.com for kia_uvo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 327, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/kia_uvo/__init__.py", line 218, in async_setup_entry
    await update(dt_util.utcnow())
  File "/config/custom_components/kia_uvo/__init__.py", line 207, in update
    datetime.now(local_timezone) - vehicle.last_updated
TypeError: can't subtract offset-naive and offset-aware datetimes
```

**Comment by nilrog** [comment] 2022-02-07 19:40
> Could someone try manually place this file changes into your home assistant? I am not from EU so can't help test. #287

Changing the API version to v2 seems to work (https://github.com/fuatakgun/kia_uvo/pull/287/files).
I have restarted HA twice now and the integration came back to life both times. No more unavailable sensors.

Here is the log output from the integration with that single change:

```
2022-02-07 20:34:54 DEBUG (MainThread) [custom_components.kia_uvo] kia_uvo - async_setup_entry started - <homeassistant.config_entries.ConfigEntry object at 0x7f53d220e0f0>
2022-02-07 20:34:54 DEBUG (MainThread) [custom_components.kia_uvo.Vehicle] kia_uvo - Received token into Vehicle Object {'valid_until': '2022-02-08 19:30:38.371685', 'access_token': 'Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaWQiOiI1YmIyYzcyMDlhOTk0MzA0MTk0MzZlYzQiLCJ1aWQiOiI5YzcxYzk4ZS0zNTBkLTRlOTgtYTFiZi1jNTdlNmY4NDY0M2YiLCJzaWQiOiI2ZDQ3N2MzOC0zY2E0LTRjZjMtOTU1Ny0yYTE5MjlhOTQ2NTQiLCJleHAiOjE2NDQzNDg2MzcsImlhdCI6MTY0NDI2MjIzNywiaXNzIjoiYmx1ZWxpbmsifQ.bzbp1aXm88vsgHWJM_ZFWbJGtA5xDTefPvIFv8tc4pUrQz-L_6_JSnpQJj0X0ydQ-Qar3ZZOa_-nVNnP8YzLbHahuq4uaVLNrl4eiIyLxPPSlXQVScnr4jJVwNpt3Nlzrwv2_Hdtwe6f5heKng2CkYqCdAeY7CymWR0aoznTlfvS1FapmdkQrYPr3miOqhMKdbvIIq_SdA4j1l3EYk9hDs47UE3GYO9L1ltD0DVWU4wg0CZWrMecCe1aY3J8Pvvf-HY-EXWxL_tozHmSTPeJAWt4tdx1bP7Kjd75hSyRfa_UUiJLMi2V9uvVIW7CwdZAnCN0PGEEN2NU1D2sjdB-CA', 'refresh_token': 'Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaWQiOiI1YmIyYzcyMDlhOTk0MzA0MTk0MzZlYzQiLCJ1aWQiOiI5YzcxYzk4ZS0zNTBkLTRlOTgtYTFiZi1jNTdlNmY4NDY0M2YiLCJzaWQiOiI2ZDQ3N2MzOC0zY2E0LTRjZjMtOTU1Ny0yYTE5MjlhOTQ2NTQiLCJleHAiOjE2NDQzNDg2MzgsImlhdCI6MTY0NDI2MjIzOCwiaXNzIjoiYmx1ZWxpbmsifQ.bPANNURpMwAGU9jyu1DIYl4aVHGUTSecik-AjgrrOATnEdXAQbnyKU2MdsokKmG2a_RriNA1s1yGlw-Yo7KfkI6jWFuznQAJmZxUUJALGig956sIl-iKOy6qhCk8vhubEMpjcXWswBHP4YhfXL9LpH3CY7vNX6T02gwZNYMew67MsDV7fIyx1ta2JAupf8qg8CxgdESiJM0YSQU3HEVe_-yKg_WE0Y_KYULNjeg2aBxdiTCT_SKDPe0MDzGR2ZLKzLFZQfH4zZMnhVX4XX6Gs_pQ0DcEzuZKp6Qp1nj9A0S9RI5rxuTsjWBf8r7NcRfdIyA0ZeFztgdbXo4-qWjIcQ', 'device_id': '**********', 'vehicle_name': 'IONIQ 5', 'vehicle_id': '**********', 'vehicle_regid': None, 'vehicle_model': 'IONIQ 5', 'vehicle_registration_date': '**********', 'stamp': 'dGpcIp3dP0dLfkNRUItk/sCdmouaEMW4JAlLv76lGxrWLqMbn3rTZi6UPSLAj9A='}
2022-02-07 20:34:54 DEBUG (MainThread) [custom_components.kia_uvo.Vehicle] kia_uvo - Refresh token started 2022-02-08 19:30:38.371685 2022-02-07 20:34:54.998550 False
2022-02-07 20:34:55 DEBUG (SyncWorker_5) [custom_components.kia_uvo.KiaUvoApiEU] kia_uvo - get_cached_vehicle_status response {'retCode': 'S', 'resCode': '0000', **********}, 'msgId': '55f60a4c-cd02-44d5-82a5-4b4d8d1c5480'}
2022-02-07 20:34:56 DEBUG (MainThread) [custom_components.kia_uvo.Vehicle] kia_uvo - LastUpdated 2022-02-07 19:18:52+01:00 - Timezone tzfile('/usr/share/zoneinfo/Europe/Berlin')
2022-02-07 20:34:56 DEBUG (MainThread) [custom_components.kia_uvo.Vehicle] kia_uvo - Engine type set VEHICLE_ENGINE_TYPE.EV
2022-02-07 20:35:05 DEBUG (MainThread) [custom_components.kia_uvo.sensor] skipping sensor for missing data, key:vehicleStatus.fuelLevel
2022-02-07 20:35:05 DEBUG (MainThread) [custom_components.kia_uvo.sensor] skipping sensor for missing data, key:vehicleStatus.evStatus.targetSOC.1.targetSOClevel
2022-02-07 20:35:05 DEBUG (MainThread) [custom_components.kia_uvo.sensor] skipping sensor for missing data, key:vehicleStatus.evStatus.targetSOC.0.targetSOClevel
2022-02-07 20:35:05 DEBUG (MainThread) [custom_components.kia_uvo.sensor] skipping sensor for missing data, key:vehicleStatus.evStatus.targetSOC.1.dte.rangeByFuel.totalAvailableRange.value
2022-02-07 20:35:05 DEBUG (MainThread) [custom_components.kia_uvo.sensor] skipping sensor for missing data, key:vehicleStatus.evStatus.targetSOC.0.dte.rangeByFuel.totalAvailableRange.value
2022-02-07 20:35:05 DEBUG (MainThread) [custom_components.kia_uvo.sensor] skipping sensor for missing data, key:lastService.value
2022-02-07 20:35:05 DEBUG (MainThread) [custom_components.kia_uvo.sensor] skipping sensor for missing data, key:nextService.value
2022-02-07 20:35:05 DEBUG (MainThread) [custom_components.kia_uvo.sensor] skipping sensor for missing data, key:vehicleLocation.geocodedLocation.display_name

```

**Comment by bkonings** [comment] 2022-02-07 19:41
Looking at that pull request, seems a bit confusing, files changed only shows:

            + ".json"
             + ".v2.json"

But the commits contain more changes, not sure what code to grab.
Probably: https://github.com/fuatakgun/kia_uvo/pull/287/commits/11a328cf6dc143e3f9dcbdb57a36167bfe22156d ?

**Comment by nilrog** [comment] 2022-02-07 19:44
> ```
>         + ".json"
>          + ".v2.json"
> ```
Yes, this is the only change I made and it is working for me now. The other two commits replaces each other so the end result is no change.

**Comment by bkonings** [comment] 2022-02-07 19:48
Ok, that seems to have worked for me.

> > ```
> >         + ".json"
> >          + ".v2.json"
> > ```
> 
> 
> Yes, this is the only change I made and it is working for me now. The other two commits replaces each other so the end result is no change.

Done the same, seems to have worked.

**Comment by LuckyTriple7** [comment] 2022-02-07 19:56
> > ```
> >         + ".json"
> >          + ".v2.json"
> > ```
> 
> Yes, this is the only change I made and it is working for me now. The other two commits replaces each other so the end result is no change.

not working for me ...

```
2022-02-07 20:55:32 ERROR (MainThread) [custom_components.kia_uvo.Vehicle] kia_uvo - Exception in update : string indices must be integers - traceback: Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/Vehicle.py", line 56, in update
    self.vehicle_data = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/kia_uvo/KiaUvoApiEU.py", line 433, in get_cached_vehicle_status
    return response["resMsg"]["vehicleStatusInfo"]
TypeError: string indices must be integers

2022-02-07 20:55:32 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry xxx@xxx.com for kia_uvo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 327, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/kia_uvo/__init__.py", line 218, in async_setup_entry
    await update(dt_util.utcnow())
  File "/config/custom_components/kia_uvo/__init__.py", line 207, in update
    datetime.now(local_timezone) - vehicle.last_updated
TypeError: can't subtract offset-naive and offset-aware datetimes
```

**Comment by nilrog** [comment] 2022-02-07 20:16
> 2022-02-07 20:55:32 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry xxx@xxx.com for kia_uvo
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 327, in async_setup
>     result = await component.async_setup_entry(hass, self)
>   File "/config/custom_components/kia_uvo/__init__.py", line 218, in async_setup_entry
>     await update(dt_util.utcnow())
>   File "/config/custom_components/kia_uvo/__init__.py", line 207, in update
>     datetime.now(local_timezone) - vehicle.last_updated
> TypeError: can't subtract offset-naive and offset-aware datetimes

Are you sure you only made that single change? This error looks like what I got when I tried an early version of the patch from @cdnninja that only contained this commit https://github.com/fuatakgun/kia_uvo/pull/287/commits/2867d5693a0a023d7b3fd5b554b6aa419677692a

 When I reverted that change and only made the **v2** change (https://github.com/fuatakgun/kia_uvo/pull/287/commits/bbe09cca9380a8c3a89c554fe0ad619db0e40063) it started working.

**Comment by cdnninja** [comment] 2022-02-07 20:21
The single change should be the v2 details as nilrog points out.   I have since merged this and generated a release since we have some good feedback on this so far.  Version will be 1.4.7.

**Comment by LuckyTriple7** [comment] 2022-02-07 20:33
> > 2022-02-07 20:55:32 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry [xxx@xxx.com](mailto:xxx@xxx.com) for kia_uvo
> > Traceback (most recent call last):
> > File "/usr/src/homeassistant/homeassistant/config_entries.py", line 327, in async_setup
> > result = await component.async_setup_entry(hass, self)
> > File "/config/custom_components/kia_uvo/**init**.py", line 218, in async_setup_entry
> > await update(dt_util.utcnow())
> > File "/config/custom_components/kia_uvo/**init**.py", line 207, in update
> > datetime.now(local_timezone) - vehicle.last_updated
> > TypeError: can't subtract offset-naive and offset-aware datetimes
> 
> Are you sure you only made that single change? This error looks like what I got when I tried an early version of the patch from @cdnninja that only contained this commit [2867d56](https://github.com/fuatakgun/kia_uvo/commit/2867d5693a0a023d7b3fd5b554b6aa419677692a)
> 
> When I reverted that change and only made the **v2** change ([bbe09cc](https://github.com/fuatakgun/kia_uvo/commit/bbe09cca9380a8c3a89c554fe0ad619db0e40063)) it started working.

Yes, only changed this ...

![image](https://user-images.githubusercontent.com/60685158/152867232-6b8bb4df-e824-48b7-b96a-def98cad9ac2.png)

**Comment by cdnninja** [comment] 2022-02-07 20:34
Something else seems to be happening.

**Comment by nilrog** [comment] 2022-02-07 21:01
@cdnninja There is still something weird going on with the authentication/request in v1.4.7.

I modified the file in v1.4.6 based on the patch and it was working fine, as I described above. And then when v1.4.7 was released I updated the integration via HACS and restarted HA...and the integration fails again :(
Tried restarting again and same result...the change that was working no longer works after updating.

This is from the log:
```
2022-02-07 21:45:07 DEBUG (MainThread) [custom_components.kia_uvo] kia_uvo - async_setup_entry started - <homeassistant.config_entries.ConfigEntry object at 0x7fc16d14a0f0>
2022-02-07 21:45:07 DEBUG (MainThread) [custom_components.kia_uvo.Vehicle] kia_uvo - Received token into Vehicle Object {'valid_until': '2022-02-08 19:30:38.371685', 'access_token': 'Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaWQiOiI1YmIyYzcyMDlhOTk0MzA0MTk0MzZlYzQiLCJ1aWQiOiI5YzcxYzk4ZS0zNTBkLTRlOTgtYTFiZi1jNTdlNmY4NDY0M2YiLCJzaWQiOiI2ZDQ3N2MzOC0zY2E0LTRjZjMtOTU1Ny0yYTE5MjlhOTQ2NTQiLCJleHAiOjE2NDQzNDg2MzcsImlhdCI6MTY0NDI2MjIzNywiaXNzIjoiYmx1ZWxpbmsifQ.bzbp1aXm88vsgHWJM_ZFWbJGtA5xDTefPvIFv8tc4pUrQz-L_6_JSnpQJj0X0ydQ-Qar3ZZOa_-nVNnP8YzLbHahuq4uaVLNrl4eiIyLxPPSlXQVScnr4jJVwNpt3Nlzrwv2_Hdtwe6f5heKng2CkYqCdAeY7CymWR0aoznTlfvS1FapmdkQrYPr3miOqhMKdbvIIq_SdA4j1l3EYk9hDs47UE3GYO9L1ltD0DVWU4wg0CZWrMecCe1aY3J8Pvvf-HY-EXWxL_tozHmSTPeJAWt4tdx1bP7Kjd75hSyRfa_UUiJLMi2V9uvVIW7CwdZAnCN0PGEEN2NU1D2sjdB-CA', 'refresh_token': 'Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaWQiOiI1YmIyYzcyMDlhOTk0MzA0MTk0MzZlYzQiLCJ1aWQiOiI5YzcxYzk4ZS0zNTBkLTRlOTgtYTFiZi1jNTdlNmY4NDY0M2YiLCJzaWQiOiI2ZDQ3N2MzOC0zY2E0LTRjZjMtOTU1Ny0yYTE5MjlhOTQ2NTQiLCJleHAiOjE2NDQzNDg2MzgsImlhdCI6MTY0NDI2MjIzOCwiaXNzIjoiYmx1ZWxpbmsifQ.bPANNURpMwAGU9jyu1DIYl4aVHGUTSecik-AjgrrOATnEdXAQbnyKU2MdsokKmG2a_RriNA1s1yGlw-Yo7KfkI6jWFuznQAJmZxUUJALGig956sIl-iKOy6qhCk8vhubEMpjcXWswBHP4YhfXL9LpH3CY7vNX6T02gwZNYMew67MsDV7fIyx1ta2JAupf8qg8CxgdESiJM0YSQU3HEVe_-yKg_WE0Y_KYULNjeg2aBxdiTCT_SKDPe0MDzGR2ZLKzLFZQfH4zZMnhVX4XX6Gs_pQ0DcEzuZKp6Qp1nj9A0S9RI5rxuTsjWBf8r7NcRfdIyA0ZeFztgdbXo4-qWjIcQ', 'device_id': '0fd91c49-36c8-4a4b-9523-914319cbf4bd', 'vehicle_name': 'IONIQ 5', 'vehicle_id': 'fd675477-21a7-40d8-bf92-a2f5da7e3f9a', 'vehicle_regid': None, 'vehicle_model': 'IONIQ 5', 'vehicle_registration_date': '**********', 'stamp': 'dGpcIp3dP0dLfkNRUItk/sCdmouaEMW4JAlLv76lGxrWLqMbn3rTZi6UPSLAj9A='}
2022-02-07 21:45:07 DEBUG (MainThread) [custom_components.kia_uvo.Vehicle] kia_uvo - Refresh token started 2022-02-08 19:30:38.371685 2022-02-07 21:45:07.569682 False
2022-02-07 21:45:07 DEBUG (SyncWorker_4) [custom_components.kia_uvo.KiaUvoApiEU] kia_uvo - get_cached_vehicle_status response {'retCode': 'F', 'resCode': '4017', 'resMsg': 'Invalid request value - Invalid Application Id. - 4027.74799990654', 'msgId': '00e958fc-0ff0-43a4-a757-1d7c22c5f09e'}
2022-02-07 21:45:09 ERROR (MainThread) [custom_components.kia_uvo.Vehicle] kia_uvo - Exception in update : string indices must be integers - traceback: Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/Vehicle.py", line 56, in update
    self.vehicle_data = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/kia_uvo/KiaUvoApiEU.py", line 433, in get_cached_vehicle_status
    return response["resMsg"]["vehicleStatusInfo"]
TypeError: string indices must be integers

2022-02-07 21:45:09 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry ***@***.*** for kia_uvo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 313, in async_setup
    await update(dt_util.utcnow())
  File "/config/custom_components/kia_uvo/__init__.py", line 207, in update
    datetime.now(local_timezone) - vehicle.last_updated
```

So I then tried deleting the integration and adding it back again, followed by a HA restart. And it works again after a restart.
I'm going to leave this running now and see if it stops working again...or if it continues to work. And later tonight, or tomorrow, I will try restarting HA again and see what happens.

**Comment by cdnninja** [comment] 2022-02-07 21:04
The stamps may be expiring. They look to refresh more frequently than they used to.

**Comment by nilrog** [comment] 2022-02-07 21:08
Could be. What was the old lifecycle for the stamps?
I can try leaving it alone, and not touching the Bluelink app, and see what happens.

**Comment by fuatakgun** [comment] 2022-02-07 22:18
Please remove the integration, download the latest version and add the integration back with same credentials.
Or, if you want to take the dangerous path, reinstall new version and manually update core.config_entries.yaml file with an expired valid_until date (anything earlier than now would work) and restart home assistant.

I have tested locally, running fine long enough

**Comment by nilrog** [comment] 2022-02-07 22:34
Yup, that's the same behavior I have seen since 1.4.6 when it looked like you fixed the problem. If you delete/install the integration it starts working. If you restart HA, or wait long enough, it stops working. And you have to repeat the steps again, and again.

Wonder what they changed since the iOS app has not been updated for a month and it still works. The change that was introduced during last night must have been in place for at least a month.

**Comment by fuatakgun** [comment] 2022-02-07 22:46
These stamps are valid for 15 minutes but i am finding the stamp while logging in and login tokens are valid for 1 day. I can just setup to login every day, but it might create issues on kia/hyundai side, i don't want to awake the beasts. I will check with bluelinky team before making a stupid move :-)

**Comment by Symbiot78** [comment] 2022-02-08 05:46
1.4.8 broke my integration.

**Comment by LuckyTriple7** [comment] 2022-02-08 06:17
> 



> Edit: taking back, please dismiss all below, no solution yet
> 
> Please remove the integration, download the latest version and add the integration back with same credentials. Or, if you want to take the dangerous path, reinstall new version and manually update core.config_entries.yaml file with an expired valid_until date (anything earlier than now would work) and restart home assistant.
> 
> I have tested locally, running fine long enough

I updated to V1.48 now and change the Date in config/storage/core.config_entries to

`"valid_until": "2022-02-08 05:40:59.378715",`

Restart HA, Integration is working. Force Refresh also working. i will keep watching it.

**Comment by LuckyTriple7** [comment] 2022-02-08 06:54
Update: Stopped working after 15 min ...

```
2022-02-08 07:52:51 DEBUG (SyncWorker_28) [custom_components._uvo.KiaUvoApiEU] kia_uvo - Received forced vehicle data {'retCode': 'F', 'resCode': '4017', 'resMsg': 'Invalid request value - Invalid Application Id. - 2001.766000032425', 'msgId': 'd7ad6b65-8a1e-467a-8478-263d871facc0'}
2022-02-08 07:52:52 DEBUG (SyncWorker_26) [custom_components.kia_uvo.KiaUvoApiEU] kia_uvo - get_cached_vehicle_status response {'retCode': 'F', 'resCode': '4017', 'resMsg': 'Invalid request value - Invalid Application Id. - 2002.0539999008179', 'msgId': '66f8eff8-ab95-4d3a-bc1f-994de53e5843'}
2022-02-08 07:52:52 ERROR (MainThread) [custom_components.kia_uvo.Vehicle] kia_uvo - Exception in update : string indices must be integers - traceback: Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/Vehicle.py", line 56, in update
    self.vehicle_data = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/kia_uvo/KiaUvoApiEU.py", line 441, in get_cached_vehicle_status
    return response["resMsg"]["vehicleStatusInfo"]
TypeError: string indices must be integers
```

**Comment by nilrog** [comment] 2022-02-08 07:11
> These stamps are valid for 15 minutes but i am finding the stamp while logging in and login tokens are valid for 1 day. I can just setup to login every day, but it might create issues on kia/hyundai side, i don't want to awake the beasts. I will check with bluelinky team before making a stupid move :-)

I have only owned this EV for a week, so I do not know how it has worked in the past.
But the current Bluelink app in EU will force you to "refresh" the status of the EV almost everytime you want to check it. And when it does that it says something like "access is valid for 10 mins". I do not know exactly what it is doing but it could be that it is logging in again to fetch a fresh token.

**Comment by mannes** [comment] 2022-02-08 08:50
broken here too, got the following errors after updating to 1.4.8
`kia_uvo - Exception in update : string indices must be integers - traceback: Traceback (most recent call last): File "/config/custom_components/kia_uvo/Vehicle.py", line 56, in update self.vehicle_data = await self.hass.async_add_executor_job( File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/kia_uvo/KiaUvoApiEU.py", line 441, in get_cached_vehicle_status return response["resMsg"]["vehicleStatusInfo"] TypeError: string indices must be integers`

and 

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 327, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/kia_uvo/__init__.py", line 218, in async_setup_entry
    await update(dt_util.utcnow())
  File "/config/custom_components/kia_uvo/__init__.py", line 207, in update
    datetime.now(local_timezone) - vehicle.last_updated
TypeError: can't subtract offset-naive and offset-aware datetimes`

**Comment by fuatakgun** [comment] 2022-02-08 09:27
We are aware of the problem, and working on a solution hopefully today (in EU timezone)

**Comment by fuatakgun** [comment] 2022-02-08 11:10
Please get v1.4.10 version, released by 12:09 PM in EU timezone.
Restart your home assistant, do not play any file, integration will take care of renewal of login token.

I am tired ;) but joyful

**Comment by LuckyTriple7** [comment] 2022-02-08 11:58
> Please get v1.4.10 version, released by 12:09 PM in EU timezone. Restart your home assistant, do not play any file, integration will take care of renewal of login token.
> 
> I am tired ;) but joyful

Thx very much :-)
Update is done, running now since one hour without errors.

**Comment by nilrog** [comment] 2022-02-08 12:00
> I am tired ;) but joyful

Enjoy a well deserved break now :)

I updated to v1.4.10 about 30 mins ago, nothing else touched, restarted HA, it started working, restarted HA again, still working, and it is still working 25 mins later, that is longer than it worked yesterday.

**Comment by egyroloine** [comment] 2022-02-08 12:11
Been running almost an hour now after uprgading and rebooting a couple of times to make sure. Still working. Good job! Thanks!

**Comment by fuatakgun** [comment] 2022-02-08 12:30
Happy to hear that, let's keep this open for 1 more day to see what will happen next :-)

**Closed** 2022-02-08 17:15 UTC

**Comment by carpaij** [comment] 2022-02-08 17:56
Thanks for the hard work and quick resolution! Working fine for over half an hour now.

just curious: was it an API change from Kia/Hyundai or was it related to some breaking changes in the the feb releases of HA?

**Comment by Symbiot78** [comment] 2022-02-08 18:05
beautifuk work as always.. much appreciated.

**Comment by cdnninja** [comment] 2022-02-08 18:20
> Thanks for the hard work and quick resolution! Working fine for over half an hour now.
> 
> 
> 
> just curious: was it an API change from Kia/Hyundai or was it related to some breaking changes in the the feb releases of HA?

It was caused by Kia Hyundai making changes to the API.
