### ISSUE TITLE
Error setting up entry for Kia_uvo - login issue

### ISSUE THREAD

**Issue by ruikenshin** [fuatakgun/kia_uvo#188] opened 2021-11-29 11:25 UTC
Hi,

Attempting to setup this integration for my 2015 Hyundai Genesis.   Upon initial setup, I was able to login with no issues but was not able to get any various entities (i.e.: Tire pressure, location).  Remote started the car just in case data didn't sync (Gotta love Bluelink availability) and waited to see if any other entities become available, but to no avail.  

Checked integration which showed failed to setup, checked logs and noted the following 

kia_uvo Exception in kia_uvo login : 'access_token' - traceback: Traceback (most recent call last): File "/config/custom_components/kia_uvo/config_flow.py", line 155, in async_step_user self.token = await self.hass.async_add_executor_job( File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/kia_uvo/HyundaiBlueLinkAPIUSA.py", line 94, in login access_token = response["access_token"] KeyError: 'access_token' 

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/kia_uvo/__init__.py", line 218, in async_setup_entry
    await update(dt_util.utcnow())
  File "/config/custom_components/kia_uvo/__init__.py", line 207, in update
    datetime.now(local_timezone) - vehicle.last_updated
TypeError: can't subtract offset-naive and offset-aware datetimes

My bluelink account has been active since 2019 and I'm in the US.

Thanks

**Comment by eopo** [comment] 2021-11-29 13:44
Similiar issue here, Kia Connect account is about 1 hour old and Region is Europe.

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/kia_uvo/__init__.py", line 218, in async_setup_entry
    await update(dt_util.utcnow())
  File "/config/custom_components/kia_uvo/__init__.py", line 207, in update
    datetime.now(local_timezone) - vehicle.last_updated
TypeError: can't subtract offset-naive and offset-aware datetimes`

`kia_uvo - Exception in update : string indices must be integers - traceback: Traceback (most recent call last): File "/config/custom_components/kia_uvo/Vehicle.py", line 56, in update self.vehicle_data = await self.hass.async_add_executor_job( File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/kia_uvo/KiaUvoApiEU.py", line 427, in get_cached_vehicle_status return response["resMsg"]["vehicleStatusInfo"] TypeError: string indices must be integers`

**Comment by cdatwood** [comment] 2021-11-29 15:47
I've also encountered this issue, fresh setup for the UVO integration this AM from HACS. Region is USA, car is KIA. 

```
Logger: homeassistant.config_entries
Source: custom_components/kia_uvo/__init__.py:207
Integration: Kia Uvo / Hyundai Bluelink (documentation, issues)
First occurred: 9:43:24 AM (1 occurrences)
Last logged: 9:43:24 AM

Error setting up entry chris@****.com for kia_uvo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/kia_uvo/__init__.py", line 218, in async_setup_entry
    await update(dt_util.utcnow())
  File "/config/custom_components/kia_uvo/__init__.py", line 207, in update
    datetime.now(local_timezone) - vehicle.last_updated
TypeError: can't subtract offset-naive and offset-aware datetimes
```

**Comment by cdnninja** [comment] 2021-11-29 16:31
These are three separate regions and three separate issues.  @eopo looks like your issue is #29.  @cdatwood  yours may be fixed in the other thread.  

@ruikenshin does your 2015 mobile app have some of this data?

**Comment by cdnninja** [comment] 2021-11-29 19:39
@ruikenshin  did some further looking at this.  Please enable debug logging from the home page of this repo.  Once done restart HA and grab me the logs.  Specifically looking for: "Sign In Response".

Now this is assuming your app shows you valuable data from your car like doors etc. If not this integration will be the same.

**Comment by cdnninja** [comment] 2021-11-30 02:52
I may have figured part of this out.  Can you edit the HyundaiBlueLinkAPIUSA.py file in your home assistant integration to change line 72 gen from 2 to 1.   If that works I can see if I can do a PR to solve this.  I will need a hand testing once confirmed though.

**Comment by ruikenshin** [comment] 2021-11-30 12:41
@cdnninja, interesting thing is that initial setup, it connects and I have logs showing what info is reported in from the data connection.  But after a period of time it loses access.

I made the above change and now unable to complete setup.  

I do have the log file that you requested.   Do you want the entire file or just reporting for the integration?

**Comment by cdnninja** [comment] 2021-11-30 17:21
Either or works.   Just so long as it shows the Kia integration.

**Comment by ruikenshin** [comment] 2021-11-30 18:27
[home-assistant gen1.log](https://github.com/fuatakgun/kia_uvo/files/7627918/home-assistant.gen1.log)
[home-assistant.log](https://github.com/fuatakgun/kia_uvo/files/7627936/home-assistant.log) - this was from last night when it actually connected but failed 3 hours later - gen 2

**Comment by cdnninja** [comment] 2021-11-30 18:39
Almost looks like your car isn't a Gen 1. I was basing this on https://github.com/Hacksore/bluelinky/issues/7. 

Looks like you don't have some sensors we are mapping that we need to handle.  I will cut a PR to solve that.

**Comment by cdnninja** [comment] 2021-11-30 18:48
Could you give this version a go? https://github.com/fuatakgun/kia_uvo/blob/b21349a10ead1daf75c53fba2b205b87ed270717/custom_components/kia_uvo/HyundaiBlueLinkAPIUSA.py

Yours logs don't seem to align to the key error you had in the initial post.  Your logs are showing missing TPMS which would cause other issues.

**Comment by ruikenshin** [comment] 2021-11-30 21:16
The logs was taking after a reboot of HA server.  

I have the above version installed, thank you, I'm currently seeing car and 16 entities.   I know why it's missing TPMS, due to app reporting so no worries there. 

I'll let it soak for a few hours and check to see if connection is still there.

**Comment by cdnninja** [comment] 2021-11-30 21:36
I have merged the above since it sounds like it solves the TPMS issue.    Lets see if your connection stays stable.

**Comment by cdnninja** [comment] 2021-12-03 03:22
I am going to go ahead and close this.  Please comment and we can reopen if further issues come up.

**Closed by cdnninja** 2021-12-03 03:22 UTC
Labels: bug, USA
