### ISSUE TITLE
Unable to login, wrong signature type

### ISSUE THREAD

**Issue by nprez83** [fuatakgun/kia_uvo#362] opened 2022-09-22 16:23 UTC
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**
USA, Kia Telluride

**Describe the bug**
The integration became unavailable, with the following log entry. I tried removing and re-adding and same error. 

**Debug logs if an error occurred**
`This error originated from a custom integration.

Logger: custom_components.kia_uvo.config_flow
Source: custom_components/kia_uvo/config_flow.py:170
Integration: Kia Uvo / Hyundai Bluelink (documentation, issues)
First occurred: 12:15:42 (1 occurrences)
Last logged: 12:15:42

kia_uvo Exception in kia_uvo login : HTTPSConnectionPool(host='api.owners.kia.com', port=443): Max retries exceeded with url: /apigw/v1/prof/authUser (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:997)'))) - traceback: Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen httplib_response = self._make_request( File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request self._validate_conn(conn) File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn conn.connect() File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 414, in connect self.sock = ssl_wrap_socket( File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket ssl_sock = _ssl_wrap_socket_impl( File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl return ssl_context.wrap_socket(sock, server_hostname=server_hostname) File "/usr/local/lib/python3.10/ssl.py", line 513, in wrap_socket return self.sslsocket_class._create( File "/usr/local/lib/python3.10/ssl.py", line 1071, in _create self.do_handshake() File "/usr/local/lib/python3.10/ssl.py", line 1342, in do_handshake self._sslobj.do_handshake() ssl.SSLError: [SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:997) During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send resp = conn.urlopen( File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen retries = retries.increment( File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment raise MaxRetryError(_pool, url, error or ResponseError(cause)) urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.owners.kia.com', port=443): Max retries exceeded with url: /apigw/v1/prof/authUser (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:997)'))) During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/config/custom_components/kia_uvo/config_flow.py", line 155, in async_step_user self.token = await self.hass.async_add_executor_job( File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/kia_uvo/KiaUvoAPIUSA.py", line 171, in login response = requests.post(url, json=data, headers=headers) File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 115, in post return request("post", url, data=data, json=json, **kwargs) File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request return session.request(method=method, url=url, **kwargs) File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request resp = self.send(prep, **send_kwargs) File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send r = adapter.send(request, **kwargs) File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 563, in send raise SSLError(e, request=request) requests.exceptions.SSLError: HTTPSConnectionPool(host='api.owners.kia.com', port=443): Max retries exceeded with url: /apigw/v1/prof/authUser (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:997)')))`

**To Reproduce**
Attempt to add the integration.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by cdnninja** [comment] 2022-09-22 17:13
Did this ever work for you?   Wondering if they changed ssl on us.  What version are you running of the integration? On Sep 22, 2022, at 10:23 AM, Numa Perez ***@***.***> wrote:﻿
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
Region and Brand of car
USA, Kia Telluride
Describe the bug
The integration became unavailable, with the following log entry. I tried removing and re-adding and same error.
Debug logs if an error occurred
`This error originated from a custom integration.
Logger: custom_components.kia_uvo.config_flow
Source: custom_components/kia_uvo/config_flow.py:170
Integration: Kia Uvo / Hyundai Bluelink (documentation, issues)
First occurred: 12:15:42 (1 occurrences)
Last logged: 12:15:42
kia_uvo Exception in kia_uvo login : HTTPSConnectionPool(host='api.owners.kia.com', port=443): Max retries exceeded with url: /apigw/v1/prof/authUser (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:997)'))) - traceback: Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen httplib_response = self._make_request( File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request self._validate_conn(conn) File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in validate_conn conn.connect() File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 414, in connect self.sock = ssl_wrap_socket( File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl.py", line 449, in ssl_wrap_socket ssl_sock = ssl_wrap_socket_impl( File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl.py", line 493, in _ssl_wrap_socket_impl return ssl_context.wrap_socket(sock, server_hostname=server_hostname) File "/usr/local/lib/python3.10/ssl.py", line 513, in wrap_socket return self.sslsocket_class._create( File "/usr/local/lib/python3.10/ssl.py", line 1071, in _create self.do_handshake() File "/usr/local/lib/python3.10/ssl.py", line 1342, in do_handshake self._sslobj.do_handshake() ssl.SSLError: [SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:997) During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send resp = conn.urlopen( File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen retries = retries.increment( File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment raise MaxRetryError(_pool, url, error or ResponseError(cause)) urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.owners.kia.com', port=443): Max retries exceeded with url: /apigw/v1/prof/authUser (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:997)'))) During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/config/custom_components/kia_uvo/config_flow.py", line 155, in async_step_user self.token = await self.hass.async_add_executor_job( File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/kia_uvo/KiaUvoAPIUSA.py", line 171, in login response = requests.post(url, json=data, headers=headers) File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 115, in post return request("post", url, data=data, json=json, **kwargs) File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request return session.request(method=method, url=url, **kwargs) File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request resp = self.send(prep, **send_kwargs) File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send r = adapter.send(request, **kwargs) File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 563, in send raise SSLError(e, request=request) requests.exceptions.SSLError: HTTPSConnectionPool(host='api.owners.kia.com', port=443): Max retries exceeded with url: /apigw/v1/prof/authUser (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:997)')))`
To Reproduce
Steps to reproduce the behavior:
Attempt to add the integration.
Expected behavior
A clear and concise description of what you expected to happen.
Screenshots
If applicable, add screenshots to help explain your problem.
Additional context
Add any other context about the problem here.

**Comment by Shayne55434** [comment] 2022-09-22 17:17
I had this working as of yesterday. I am now getting the same message. Looks like everything went "Unavailable" around 11:30PM, last night.

I think they may have changed SSL settings.

**Comment by nprez83** [comment] 2022-09-22 19:27
Yeah, I've been using this integration for months, stopped working yesterday sometime.

**Comment by cdnninja** [comment] 2022-09-22 20:16
Did you recently update home assistant? On Sep 22, 2022, at 1:27 PM, Numa Perez ***@***.***> wrote:﻿
Yeah, I've been using this integration for months, stopped working yesterday sometime.

**Comment by nprez83** [comment] 2022-09-22 20:42
I updated the core to 2022.9.5 on Sunday, and to 2022.9.6 today, but the problem started yesterday, so don't think it's related to any updates on my end.

**Comment by nprez83** [comment] 2022-09-22 20:46
This is the error I get in the UI btw "Login failed into Kia Uvo / Hyundai Bluelink Servers. Please use official Kia Uvo app to logout and log back in and try again!". I wonder if the issue may be related to the Bluelinky api.

**Comment by alexwhittemore** [comment] 2022-09-23 15:42
Same experience as everyone else. It IS possible that the errors for me correspond with a HASS update but I’m not totally clear on the timeline.

**Comment by ThomasEAK** [comment] 2022-09-23 15:50
Same errors and attempt to logout/ login the official app.

One addition: my error started the same day as others, but I have not updated to this months HA at all (I only update on the 28th right before the next release).

**Comment by cdnninja** [comment] 2022-09-23 18:58
I assume ciphers have changed much like the Hyundai USA side. I will work on a PR to allow weak ciphers.  The error is the same as we had with Hyundai about a year ago.

**Comment by cdnninja** [comment] 2022-09-23 20:07
#363  should resolve this issue.

**Comment by nprez83** [comment] 2022-09-23 21:35
Just imported the updated file manually and everything seems to be working well. Thanks for the prompt fix, much appreciated!

**Comment by cdnninja** [comment] 2022-09-24 16:12
I am going to close this out.  The latest version should resolve.

**Closed by cdnninja** 2022-09-24 16:12 UTC

**Comment by alexwhittemore** [comment] 2022-09-24 16:44
Just updated and all seems well over here!

thanks so much for the super quick fix!

**Comment by alexwhittemore** [comment] 2022-09-26 17:49
Kind of wild - my 12V battery telemetry (in an EV6) came back after this update too! That makes no sense to me, but I'm pleased :)
