### ISSUE TITLE
Service to open charging port door

### ISSUE THREAD

**Issue by elektrinis** [fuatakgun/kia_uvo#401] opened 2022-11-02 09:24 UTC
I'd love to automate door opening when I pick up the cable (my EVSE has the sensor). Or at least it is much more convenient to tap a button on my tablet that I have on the fridge instead of trying to do this from native bluelink app.

**Comment by elektrinis** [comment] 2022-11-07 13:48
It's IONIQ 5, EU.
Sorry I did not check for open items. You may close this if it's duplicate.

**Comment by cdnninja** [comment] 2022-11-07 18:29
Duplicate of #243 . Closing.

**Closed by cdnninja** 2022-11-07 18:29 UTC
Labels: enhancement
