### ISSUE TITLE
Login Issue: Login failed into Kia Uvo / Hyundai Bluelink Servers. Please use official Kia Uvo app to logout and log back in and try again!

### ISSUE THREAD

**Issue by pfish3r** [fuatakgun/kia_uvo#118] opened 2021-11-09 18:45 UTC
Hi,

I have tried sharing accounts etc as mentioned in similar posts, i have checked username and password a number of times but am not able to log in still.  Error details below.

Any help gratefully received.

Thanks

This error originated from a custom integration.

Logger: custom_components.kia_uvo.config_flow
Source: custom_components/kia_uvo/config_flow.py:169
Integration: Kia Uvo / Hyundai Bluelink (documentation, issues)
First occurred: 18:25:37 (6 occurrences)
Last logged: 18:38:40

kia_uvo Exception in kia_uvo login : 'NoneType' object is not subscriptable - traceback: Traceback (most recent call last): File "/config/custom_components/kia_uvo/config_flow.py", line 154, in async_step_user self.token = await self.hass.async_add_executor_job( File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/kia_uvo/KiaUvoApiEU.py", line 78, in login credentials = push_receiver.register(sender_id=self.GCM_SENDER_ID) File "/usr/local/lib/python3.9/site-packages/push_receiver/push_receiver.py", line 204, in register fcm = fcm_register(sender_id=sender_id, token=subscription["token"]) TypeError: 'NoneType' object is not subscriptable
kia_uvo Exception in kia_uvo login : no session id returned in login. Response: {"status":{"statusCode":1,"errorType":1,"errorCode":1001,"errorMessage":"Invalid Email or Password"}} headers {'Server': 'KMA', 'Date': 'Tue, 09 Nov 2021 18:38:40 GMT', 'Content-length': '101', 'Content-type': 'application/json', 'Xid': '877a307e-b5a6-43a6-ac13-7d53a63497c4'} cookies <RequestsCookieJar[]> - traceback: Traceback (most recent call last): File "/config/custom_components/kia_uvo/config_flow.py", line 154, in async_step_user self.token = await self.hass.async_add_executor_job( File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/kia_uvo/KiaUvoAPIUSA.py", line 91, in login raise Exception(f"no session id returned in login. Response: {response.text} headers {response.headers} cookies {response.cookies}") Exception: no session id returned in login. Response: {"status":{"statusCode":1,"errorType":1,"errorCode":1001,"errorMessage":"Invalid Email or Password"}} headers {'Server': 'KMA', 'Date': 'Tue, 09 Nov 2021 18:38:40 GMT', 'Content-length': '101', 'Content-type': 'application/json', 'Xid': '877a307e-b5a6-43a6-ac13-7d53a63497c4'} cookies <RequestsCookieJar[]>

**Comment by dahlb** [comment] 2021-11-09 18:54
there has been a lot of activity on the USA implementation are you sure you're using the latest version?  It works for my login and another USA user I talked to this morning, have you tried making a password without special characters? might be an encoding issue with your password

**Comment by RubenKremer** [comment] 2021-11-09 19:50
I second the question. I also am unable to sign into Bluelink -using the integration - I never have. The password I used has no characters which could easily be misinterpreted. 

`Logger: custom_components.kia_uvo.config_flow
Source: custom_components/kia_uvo/config_flow.py:169
Integration: Kia Uvo / Hyundai Bluelink (documentation, issues)
First occurred: 7 november 2021 22:09:36 (8 occurrences)
Last logged: 20:44:02

kia_uvo Exception in kia_uvo login : 'redirectUrl' - traceback: Traceback (most recent call last): File "/config/custom_components/kia_uvo/config_flow.py", line 154, in async_step_user self.token = await self.hass.async_add_executor_job( File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/kia_uvo/KiaUvoApiEU.py", line 151, in login parsed_url = urlparse(response.json()["redirectUrl"]) KeyError: 'redirectUrl'
kia_uvo Exception in kia_uvo login : 'NoneType' object is not subscriptable - traceback: Traceback (most recent call last): File "/config/custom_components/kia_uvo/config_flow.py", line 154, in async_step_user self.token = await self.hass.async_add_executor_job( File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/kia_uvo/KiaUvoApiEU.py", line 78, in login credentials = push_receiver.register(sender_id=self.GCM_SENDER_ID) File "/usr/local/lib/python3.9/site-packages/push_receiver/push_receiver.py", line 204, in register fcm = fcm_register(sender_id=sender_id, token=subscription["token"]) TypeError: 'NoneType' object is not subscriptable`

**Comment by florafrisia** [comment] 2021-11-09 21:04
Hello,

I think I have the same issue as the others EV users.
Hyundai Kona, Europe

kia_uvo Exception in kia_uvo login : 'redirectUrl' - traceback: Traceback (most recent call last): File "/config/custom_components/kia_uvo/config_flow.py", line 154, in async_step_user self.token = await self.hass.async_add_executor_job( File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/kia_uvo/KiaUvoApiEU.py", line 151, in login parsed_url = urlparse(response.json()["redirectUrl"]) KeyError: 'redirectUrl'

With kind regards,

Peter Noé

**Comment by fuatakgun** [comment] 2021-11-09 22:39
@florafrisia and @RubenKremer , please track this over here: https://github.com/fuatakgun/kia_uvo/issues/79

**Comment by fuatakgun** [comment] 2021-11-09 22:40
@pfish3r your error seems very weird, it is a mix of EU and US.

Please start from scratch and share error logs

**Comment by cdnninja** [comment] 2021-11-11 22:12
Let us know what you find.  Since you are actually EU this may be a duplicate of 79.

**Comment by fuatakgun** [comment] 2021-11-12 19:12
resolving this thread and merging into: https://github.com/fuatakgun/kia_uvo/issues/79

**Closed by fuatakgun** 2021-11-12 19:12 UTC
Labels: EU

**Comment by pfish3r** [comment] 2021-11-16 13:25
Hi,  sorry only just been able to get back on this.  I created a brand new homeassitant deployment but still get the same issue.  I have used a hyper-v vhd to deploy.  I think i'll start again but on a Raspberry Pi in case there is some language differences embedded in the vm image.

**Comment by pfish3r** [comment] 2021-11-22 18:47
Hi, version 1.1.0 fixed this issue for me!  Thank you.

**Comment by florafrisia** [comment] 2021-11-22 20:29
For me to, thanks
