### ISSUE TITLE
Seat heater status is shown incorrectly

### ISSUE THREAD

**Issue by marian-gavornik** [fuatakgun/kia_uvo#239] opened 2022-01-09 20:27 UTC
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
Europe, Hyundai Tucson NX4, HEV

**Describe the bug**
Seat heaters showing as turned on, although they are turned off 

**Debug logs if an error occurred**

Outlined here: https://github.com/fuatakgun/kia_uvo/blob/master/README.m

**To Reproduce**

**Expected behavior**
Just to show correct status of seat heater(s)

**Screenshots**
![Snímka obrazovky 2022-01-09 o 21 26 07](https://user-images.githubusercontent.com/96845407/148699516-55065909-65bc-4703-bcef-3bde5232ad85.png)

**Additional context**

**Comment by cdnninja** [comment] 2022-01-10 02:53
This is a duplicate of #195

**Closed by cdnninja** 2022-01-10 02:53 UTC
