### ISSUE TITLE
set_charge_limits for Hyundai EU

### ISSUE THREAD

**Issue by Growiel** [fuatakgun/kia_uvo#353] opened 2022-08-30 21:52 UTC
Hello,

I was working on automating the charge of my car to 100% once a month to preseve battery life.

It looks like the `set_charge_limits` service does not work, the documentation here does state that it's "USA Kia Only".

So my question is: what is needed to make it work with Hyundai EU ? I'm fairly tech savy, I can provide any help needed, because it is available from the app, so no reason we can't do the same.

Thanks !

**Comment by Danielhiversen** [comment] 2022-09-05 19:21
@Growiel Have you seen this?
https://github.com/fuatakgun/kia_uvo/pull/310

**Comment by Growiel** [comment] 2022-09-05 20:15
I did not, any ideas on what we can do to speed the merge along ?

**Comment by fuatakgun** [comment] 2022-09-05 20:18
Oh man, i totally missed this, can you also please give it a try and i can merge if it is also working for you.

**Comment by cdnninja** [comment] 2022-09-10 01:07
#310 only merges to the external API branch.  That branch was intended as a re-write.    To implement this we need to implement in the EU API.

**Comment by jwefers** [comment] 2022-09-10 08:17
is the externalAPI branch still the indended way to go forward? @cdnninja

**Comment by cdnninja** [comment] 2022-09-10 15:00
Longer term it was supposed to be version 2.0.  I ran out of steam and lacked testers though. It fixes things like multi car support.

**Comment by rindlerblabla** [comment] 2022-09-18 06:01
Sorry, a newbie question. Is it possible to use the external api somehow? Am interested in this feature as well (EU).

**Comment by cdnninja** [comment] 2022-09-18 19:36
I created PR #357 could someone test it out?   I haven't tested it in any way so wouldn't doubt it if it throws errors.   Feel free to edit it if required.

**Comment by gasman1844** [comment] 2022-09-26 07:57
I'm in the UK and I'm happy to test this out. I've used HACS to install the main integration - how do I install a test branch?

**Comment by mathiasmarkussen** [comment] 2022-09-29 13:54
I copied the KiaUvoApiEU.py from the PR to replace the one I had. There are two errors in the new file. First, in line 637 `token.id` should be `token.vehicle_id`. Then, in line 642 `"Stamp": self._get_stamp()`, should be `"Stamp": self.get_stamp()`.
The service works for me now :)
I'm in Denmark, and can also help out if testing is needed for more / better functionality :)

**Comment by rindlerblabla** [comment] 2022-09-29 18:01
Can confirm that the PR with the changes suggested by @mathiasmarkussen is working. Thanks a lot!

**Comment by cdnninja** [comment] 2022-09-29 18:45
@mathiasmarkussen  always happy to have PRs created.  Thanks for the help on testing and fixing my PR.  The externalAPI branch has to be manually installed but the goal was to switch to that re-write one day.   It fixes some of the core issues with this integration but is essentially a full rewrite.    It does multiple cars, can fix seat heater issues in some version etc.

**Comment by cdnninja** [comment] 2022-09-29 18:53
This is now merged.  Please pull the latest version from HACS to test.  It also has consumption sensors added so testing is appreciated.  A version release will auto occur this weekend by github.

**Closed by cdnninja** 2022-09-29 18:53 UTC
